version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - /docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - project-network
  logstash:
    image: logstash:6.8.8
    container_name: logstash
    ports:
      - 4560:4560
    volumes:
      - /docker/logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    networks:
      - project-network
  kibana:
    image: kibana:6.8.8
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - project-network
networks:
  project-network:
    external: true