version: '3'
services:
  chic-portal:
    image: registry.cn-chengdu.aliyuncs.com/septillions/chic-portal
    container_name: chic-portal
    ports:
      - 8081:8080
    volumes:
      - /docker/chic-portal/logs:/logs
      - /docker/skywalking:/skywalking
      - /etc/localtime:/etc/localtime:ro
    environment:
      SPRING_PROFILES_ACTIVE: test
      TZ: Asia/Shanghai
    networks:
      - project-network
  chic-admin:
    image: registry.cn-chengdu.aliyuncs.com/septillions/chic-admin
    container_name: chic-admin
    ports:
      - 8082:8080
    volumes:
      - /docker/chic-admin/logs:/logs
      - /docker/skywalking:/skywalking
      - /etc/localtime:/etc/localtime:ro
    environment:
      SPRING_PROFILES_ACTIVE: test
      TZ: Asia/Shanghai
    networks:
      - project-network
networks:
  project-network:
    external: true