version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /docker/nginx/logs:/var/log/nginx
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      - project-network
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /docker/mysql/logs:/logs
      - /docker/mysql/data:/var/lib/mysql
      - /docker/mysql/conf:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - project-network
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /docker/redis/data:/data
      - /docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    command: redis-server /etc/redis/redis.conf
    networks:
      - project-network
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /docker/rabbitmq:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    environment:
      RABBITMQ_DEFAULT_USER: chic
      RABBITMQ_DEFAULT_PASS: chic
    networks:
      - project-network
networks:
  project-network:
    external: true