spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/chic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # Redis
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: localhost
    # 端口号
    port: 6379
    # 密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms