# 开发环境
spring:
  profiles:
    active: dev

# Logback
logging:
  config: classpath:logback-${spring.profiles.active}.xml

# MyBatis Plus
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT
jwt:
  # JWT 加解密使用的密钥
  secret: JWTSecret
  # JWT 存储的请求头
  header: Authorization
  # JWT AccessToken 过期时间(60*60*24*7 604800)
  access-token-expire-time: 604800
  # JWT RefreshToken 过期时间(60*60*24*30 2592000)
  refresh-token-expire-time: 2592000
  # JWT BufferToken 过期时间(60*5 300)
  buffer-token-expire-time: 300

# 认证
auth:
  # 忽略认证的接口
  ignore:
    # POST 请求
    post:
      - /auth/register
      - /auth/login
      - /auth/logout
      - /auth/refresh

# 缓存
cache:
  # Cache 默认过期时间(60*60*24*7 604800)
  default-expire-time: 604800
