spring:
  # MySQL
  datasource:
    url: jdbc:mysql://mysql:3306/chic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # Druid
    druid:
      # 初始化连接数
      initialSize: 1
      # 最小连接数
      minIdle: 1
      # 最大连接数
      maxActive: 20
      # 获取连接超时时间
      maxWait: 2000
      # 连接有效性检测间隔时间
      timeBetweenEvictionRunsMillis: 60000
      # 连接最小生存时间
      minEvictableIdleTimeMillis: 600000
      # PSCache
      poolPreparedStatements: true
      # 连接 PSCache 大小
      maxOpenPreparedStatements: 100
      # 获取连接时检测
      testOnBorrow: false
      # 放回连接时检测
      testOnReturn: false
      # 空闲时检测
      testWhileIdle: true
      # 检测连接的查询语句
      validationQuery: SELECT 1
      # 监控统计拦截的 filters
      filters: stat,wall
      # 监控页面
      statViewServlet:
        enabled: true
        loginUsername: admin
        loginPassword: admin
        resetEnable: false
        urlPattern: /druid/*
      # 网络统计
      webStatFilter:
        enabled: true
        urlPattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  # Redis
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: redis
    # 端口号
    port: 6379
    # 密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    lettuce:
      # 连接池
      pool:
        # 最大连接数（使用负值表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

  # RabbitMQ
  rabbitmq:
    host: 192.168.10.24
    port: 5672
    username: chic
    password: chic
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: simple
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 5000
          multiplier: 2
          max-attempts: 10
          max-interval: 86400000