# 开发环境
spring:
  profiles:
    active: dev

# Logback
logging:
  config: classpath:logback-${spring.profiles.active}.xml

# MyBatis Plus
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT
jwt:
  # JWT 加解密使用的密钥
  secret: JWTSecret
  # JWT 存储的请求头
  header: Authorization
  # JWT 超期限时间(60*60*24*7 604800)
  expiration: 604800

# 认证
auth:
  # 不需要认证的接口
  ignores:
    # POST 请求
    post:
      - /auth/login
      - /auth/register