spring:
  # MySQL
  datasource:
    url: jdbc:mysql://mysql:3306/chic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # HikariCP
    hikari:
      # 空闲时保持最小连接数
      minimum-idle: 2
      # 最大连接数
      maximum-pool-size: 20
      # 空闲连接存活时间
      idle-timeout: 600000
      # 连接最大存活时间
      max-lifetime: 1200000
      # 连接超时时间
      connection-timeout: 3000
      # 连接有效性检测语句
      connection-test-query: SELECT 1

  # Redis
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: redis
    # 端口号
    port: 6379
    # 密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    lettuce:
      # 连接池
      pool:
        # 最大连接数（使用负值表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

# Knife4j
# https://doc.xiaominfo.com/
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽文档
  production: true
  setting:
    # 显示 Swagger Model
    enable-swagger-models: true
    # 显示文档管理
    enable-document-manage: true
    # 显示 Footer
    enable-footer: false
    # 开启版本控制
    enable-version: true
