spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/chic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 3000ms